const devData = `
  {
    "title": "大地魔法・単Ｃ",
    "material": "大地",
    "target": 0,
    "yLine": 2,
    "frame": 25,
    "cells": [
      {
        "frame": 1,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -8,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 2,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -24,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 3,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -48,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 4,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -72,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 5,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -104,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 6,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -136,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 7,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -144,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 8,
        "no": 1,
        "visible": false,
        "pattern": 2,
        "x": -16,
        "y": -144,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 9,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": 8,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 10,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": -16,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 11,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": -40,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 12,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": -80,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 13,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": -112,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 14,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": -48,
        "y": -144,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 15,
        "no": 1,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": -136,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 16,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -48,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 17,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -72,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 18,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -104,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 19,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -136,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 20,
        "no": 1,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -144,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 21,
        "no": 1,
        "visible": false,
        "pattern": 2,
        "x": -16,
        "y": -144,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 22,
        "no": 1,
        "visible": false,
        "pattern": 1,
        "x": -48,
        "y": 8,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 23,
        "no": 1,
        "visible": false,
        "pattern": 1,
        "x": -48,
        "y": -24,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 24,
        "no": 1,
        "visible": false,
        "pattern": 1,
        "x": -48,
        "y": -48,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 25,
        "no": 1,
        "visible": false,
        "pattern": 1,
        "x": -48,
        "y": -80,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 1,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 2,
        "no": 2,
        "visible": true,
        "pattern": 3,
        "x": 48,
        "y": -32,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 3,
        "no": 2,
        "visible": true,
        "pattern": 3,
        "x": 48,
        "y": -64,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 4,
        "no": 2,
        "visible": true,
        "pattern": 3,
        "x": 48,
        "y": -104,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 5,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -32,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 6,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 7,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 8,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -96,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 9,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -128,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 10,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 11,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": -24,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 12,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": -48,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 13,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": -72,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 14,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": -96,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 15,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": -120,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 16,
        "no": 2,
        "visible": false,
        "pattern": 3,
        "x": 48,
        "y": -64,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 17,
        "no": 2,
        "visible": false,
        "pattern": 3,
        "x": 48,
        "y": -104,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 18,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -32,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 19,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 20,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 21,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -96,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 22,
        "no": 2,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -128,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 23,
        "no": 2,
        "visible": false,
        "pattern": 2,
        "x": -8,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 24,
        "no": 2,
        "visible": false,
        "pattern": 2,
        "x": -8,
        "y": -24,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 25,
        "no": 2,
        "visible": false,
        "pattern": 2,
        "x": -8,
        "y": -48,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 1,
        "no": 3,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": 0,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 2,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 3,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 4,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -16,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 5,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 6,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -48,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 7,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": 16,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 8,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -8,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 9,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -40,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 10,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 11,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -104,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 12,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -144,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 13,
        "no": 3,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 14,
        "no": 3,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": -96,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 15,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": -24,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 16,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 17,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -16,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 18,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 19,
        "no": 3,
        "visible": true,
        "pattern": 2,
        "x": -32,
        "y": -48,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 20,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": 16,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 21,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -8,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 22,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -40,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 23,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -64,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 24,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -104,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 25,
        "no": 3,
        "visible": true,
        "pattern": 4,
        "x": 0,
        "y": -144,
        "scale": 80,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 1,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 48,
        "y": -8,
        "scale": 200,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 2,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": 0,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 3,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -24,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 4,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -40,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 5,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -40,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 6,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -96,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 7,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -104,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 8,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -136,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 9,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 8,
        "y": 0,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 10,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 8,
        "y": -8,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 11,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 8,
        "y": -48,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 12,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 8,
        "y": -80,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 13,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 8,
        "y": -104,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 14,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": -16,
        "y": 0,
        "scale": 150,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 15,
        "no": 4,
        "visible": false,
        "pattern": 2,
        "x": 8,
        "y": -104,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 16,
        "no": 4,
        "visible": false,
        "pattern": 3,
        "x": 16,
        "y": -24,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 17,
        "no": 4,
        "visible": false,
        "pattern": 3,
        "x": 16,
        "y": -40,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 18,
        "no": 4,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -40,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 19,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -96,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 20,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -104,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 21,
        "no": 4,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -136,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 22,
        "no": 4,
        "visible": false,
        "pattern": 2,
        "x": 8,
        "y": 0,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 23,
        "no": 4,
        "visible": false,
        "pattern": 2,
        "x": 8,
        "y": -8,
        "scale": 70,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 1,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 2,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 3,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -8,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 4,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -24,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 5,
        "no": 5,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -64,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 6,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 7,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -80,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 8,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -112,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 9,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -8,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 10,
        "no": 5,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": 24,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 11,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -48,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 12,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -48,
        "y": -24,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 13,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -48,
        "y": -56,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 14,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -48,
        "y": -80,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 15,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": -48,
        "y": -96,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 16,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -8,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 17,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -24,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 18,
        "no": 5,
        "visible": true,
        "pattern": 3,
        "x": 16,
        "y": -64,
        "scale": 125,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 19,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -64,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 20,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -80,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 21,
        "no": 5,
        "visible": true,
        "pattern": 2,
        "x": 40,
        "y": -112,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 22,
        "no": 5,
        "visible": false,
        "pattern": 2,
        "x": -8,
        "y": 0,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 23,
        "no": 5,
        "visible": false,
        "pattern": 1,
        "x": 24,
        "y": 24,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 50
      },
      {
        "frame": 7,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -56,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 8,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -88,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 9,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -112,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 10,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -136,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 11,
        "no": 6,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": 0,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 25
      },
      {
        "frame": 12,
        "no": 6,
        "visible": true,
        "pattern": 1,
        "x": 24,
        "y": -32,
        "scale": 100,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 20,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -56,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 21,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -88,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 22,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -112,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      },
      {
        "frame": 23,
        "no": 6,
        "visible": true,
        "pattern": 2,
        "x": 16,
        "y": -136,
        "scale": 50,
        "r": 100,
        "g": 100,
        "b": 100,
        "sat": 100,
        "alpha": 100
      }
    ],
    "effects": [
      {
        "frame": 1,
        "sound": {
          "file": "大地4",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 0,
          "r": 31,
          "g": 31,
          "b": 31,
          "volume": 0
        }
      },
      {
        "frame": 3,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 10
        }
      },
      {
        "frame": 5,
        "sound": {
          "file": "大地5",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 0,
          "r": 31,
          "g": 31,
          "b": 31,
          "volume": 0
        }
      },
      {
        "frame": 9,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 0
        }
      },
      {
        "frame": 12,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 0
        }
      },
      {
        "frame": 15,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 0
        }
      },
      {
        "frame": 18,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 0
        }
      },
      {
        "frame": 21,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 0
        }
      },
      {
        "frame": 24,
        "sound": {
          "file": "(OFF)",
          "volume": 100,
          "pitch": 100,
          "pan": 50
        },
        "flash": {
          "area": 1,
          "r": 25,
          "g": 10,
          "b": 5,
          "volume": 20
        }
      }
    ]
  }
`
export default devData
